#!/usr/bin/ruby

begin
  require 'hirb'
  Hirb.enable; puts 'hirb enabled'
rescue LoadError
end

def log(stream = STDOUT)
  require 'logger'
  logger = Logger.new(stream)
  if Rails.respond_to?(:logger=)
    Rails.logger = logger
  else
    silence_warnings do
      Object.const_set :RAILS_DEFAULT_LOGGER, logger
    end
  end
  if defined? ActiveRecord::Base
    ActiveRecord::Base.logger = logger
    if Rails::VERSION::MAJOR >= 2 and Rails::VERSION::MINOR >= 2
      ActiveRecord::Base.connection_pool.clear_reloadable_connections!
    else
      ActiveRecord::Base.clear_active_connections!
    end
  end
  logger
end

def sql(query)
  ActiveRecord::Base.connection.select_all(query)
end

