#!/usr/bin/ruby

begin
  require 'hirb' # sudo gem install hirb
  Hirb.enable
rescue LoadError
end

def change_log(stream)
  require 'logger'
  logger = Logger.new(stream)
  if Rails.respond_to?(:logger=)
    Rails.logger = logger
  else
    silence_warnings do
      Object.const_set :RAILS_DEFAULT_LOGGER, logger
    end
  end
  if defined? ActiveRecord::Base
    ActiveRecord::Base.logger = logger
    ActiveRecord::Base.clear_active_connections!
  end
  if defined? ActionController::Base
    ActionController::Base.logger = logger
  end
  if defined? ActiveResource::Base
    ActiveResource::Base.logger = logger
  end
  logger
end

def show_log
  change_log(STDOUT)
end

def hide_log
  change_log(nil)
end
